import React, { useState, useEffect } from 'react';
import { ServicePlan, SubscriptionTier, User } from '../types';
import { Plus, Trash2, Wand2, Music, Mic, User as UserIcon, Mic2, UserCheck, PlayCircle, Lock, Loader2, Paperclip, FileText, X, Hand, BookOpen, DollarSign, Megaphone, MessageCircle, Gift, Heart, Star, PenTool } from 'lucide-react';
import { generateSermonOutline } from '../services/geminiService';
import { usePlans } from '../hooks/usePlans';
import { uploadFile, deleteFile } from '../services/storageService';

interface ServicePlannerProps {
  tier: SubscriptionTier;
  users: User[];
}

const ROLES_CONFIG = [
  { key: 'elder', label: 'Anciano de Turno', icon: UserCheck, color: 'text-blue-500 bg-blue-50', role: 'ELDER' },
  { key: 'preacher', label: 'Predicador', icon: Mic2, color: 'text-purple-500 bg-purple-50', role: 'PREACHER' },
  { key: 'worshipLeader', label: 'Director de Música', icon: Music, color: 'text-pink-500 bg-pink-50', role: 'MUSIC' },
  { key: 'audioOperator', label: 'Operador de Audio', icon: Mic, color: 'text-orange-500 bg-orange-50', role: 'AUDIO' },
];

const ServicePlanner: React.FC<ServicePlannerProps> = ({ tier, users }) => {
  const { plans, loading, savePlan, deletePlan } = usePlans();
  const [selectedPlanId, setSelectedPlanId] = useState<string>('');

  const [isAiLoading, setIsAiLoading] = useState(false);
  const [showAiModal, setShowAiModal] = useState(false);
  const [aiParams, setAiParams] = useState({ passage: '', tone: 'Exhortativo', targetItemId: '' });

  // Add Item State
  const [showAddItemModal, setShowAddItemModal] = useState(false);
  const [newItem, setNewItem] = useState({
    title: '',
    durationMinutes: 5,
    type: 'WORSHIP' as 'WORSHIP' | 'PREACHING' | 'GENERIC',
    key: ''
  });

  const handleAddItem = async () => {
    if (!selectedPlan) return;

    const itemToAdd = {
      id: Math.random().toString(36).substr(2, 9),
      title: newItem.title,
      durationMinutes: newItem.durationMinutes,
      type: newItem.type,
      key: newItem.key,
      notes: ''
    };

    const updatedItems = [...selectedPlan.items, itemToAdd];
    await savePlan({ ...selectedPlan, items: updatedItems });

    setShowAddItemModal(false);
    setNewItem({ title: '', durationMinutes: 5, type: 'WORSHIP', key: '' });
  };

  // Derive selectedPlan safely
  const selectedPlan = plans.find(p => p.id === selectedPlanId) || plans[0];

  // Effect to ensure a plan is always selected if available
  useEffect(() => {
    if (plans.length > 0 && !selectedPlanId) {
      setSelectedPlanId(plans[0].id);
    }
  }, [plans, selectedPlanId]);

  // Feature Flag
  const canUseAI = tier === 'PLATINUM';

  const toggleActivePlan = async (id: string) => {
    if (!selectedPlan) return;

    // If we are activating this plan, we should deactivate others (optional but good practice)
    // For now, just toggle current
    const updated = { ...selectedPlan, isActive: !selectedPlan.isActive };
    await savePlan(updated);
  };

  const calculateTimeline = (plan: ServicePlan) => {
    let currentTime = new Date(`2000-01-01T${plan.startTime}`);
    return plan.items.map(item => {
      const timeStr = currentTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      currentTime.setMinutes(currentTime.getMinutes() + item.durationMinutes);
      return { ...item, calculatedTime: timeStr };
    });
  };

  const handleAiGenerate = async () => {
    setIsAiLoading(true);
    try {
      const outline = await generateSermonOutline(aiParams.passage, aiParams.tone);

      if (selectedPlan) {
        const updatedItems = selectedPlan.items.map(item =>
          item.id === aiParams.targetItemId ? { ...item, notes: outline } : item
        );
        await savePlan({ ...selectedPlan, items: updatedItems });
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsAiLoading(false);
      setShowAiModal(false);
    }
  };

  const openAiModal = (itemId: string) => {
    if (!canUseAI) return;
    setAiParams(prev => ({ ...prev, targetItemId: itemId }));
    setShowAiModal(true);
  }

  const handleTeamChange = async (roleKey: string, value: string) => {
    if (!selectedPlan) return;
    const updated = {
      ...selectedPlan,
      team: { ...selectedPlan.team, [roleKey]: value }
    };
    await savePlan(updated);
  };

  const handleCreatePlan = async () => {
    const newPlan: ServicePlan = {
      id: '', // Will be generated by hook
      date: new Date().toISOString().split('T')[0],
      title: 'Nuevo Servicio',
      startTime: '10:00',

      team: {
        musicDirector: '',
        audioOperator: '',
        preacher: '',
        elder: ''
      },
      items: [],
      isActive: false
    };
    const saved = await savePlan(newPlan);
    setSelectedPlanId(saved.id);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="animate-spin text-indigo-500" size={32} />
      </div>
    );
  }

  // If no plans exist, show empty state or create button
  if (plans.length === 0 && !loading) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-500 space-y-4">
        <p>No hay planes de servicio creados.</p>
        <button
          onClick={handleCreatePlan}
          className="flex items-center gap-2 bg-indigo-600 text-white px-6 py-3 rounded-xl font-bold hover:bg-indigo-500 transition-colors"
        >
          <Plus size={20} /> Crear Primer Plan
        </button>
      </div>
    );
  }

  const handleTeamUpdate = async (roleKey: string, name: string) => {
    if (!selectedPlan) return;
    const updatedTeam = { ...selectedPlan.team, [roleKey]: name };
    await savePlan({ ...selectedPlan, team: updatedTeam });
  };

  const timelineItems = selectedPlan ? calculateTimeline(selectedPlan) : [];

  return (
    <div className="p-4 md:p-8 md:pt-24 max-w-full mx-auto space-y-8 pb-32">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold text-slate-800">Orden de Cultos</h2>
          <p className="text-slate-500">Diseña el flujo del servicio y gestiona el equipo.</p>
        </div>

        <div className="flex items-center gap-2 bg-white p-1 rounded-full border border-slate-200 shadow-sm">
          {plans.map(plan => (
            <button
              key={plan.id}
              onClick={() => setSelectedPlanId(plan.id)}
              className={`px-4 py-2 rounded-full text-xs font-bold transition-all ${selectedPlanId === plan.id
                ? 'bg-slate-800 text-white shadow-md'
                : 'text-slate-500 hover:bg-slate-50'
                }`}
            >
              {plan.title}
            </button>
          ))}
          <button
            onClick={handleCreatePlan}
            className="w-8 h-8 flex items-center justify-center rounded-full bg-indigo-50 text-indigo-600 hover:bg-indigo-100 transition-colors"
          >
            <Plus size={16} />
          </button>
        </div>

        {selectedPlan && (
          <button
            onClick={async () => {
              if (confirm('¿Estás seguro de eliminar este plan?')) {
                await deletePlan(selectedPlan.id);
                // After deletion, select the first available plan or clear selection
                if (plans.length > 1) {
                  setSelectedPlanId(plans.filter(p => p.id !== selectedPlan.id)[0]?.id || '');
                } else {
                  setSelectedPlanId(''); // No plans left
                }
              }
            }}
            className="ml-4 p-3 bg-red-50 text-red-500 rounded-xl hover:bg-red-100 transition-colors"
            title="Eliminar Plan Actual"
          >
            <Trash2 size={20} />
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

        {/* Left Col: Roster & Controls */}
        <div className="space-y-6">
          {/* Active Toggle Card (Only Admin/Tech) */}
          {tier !== 'BASIC' && ( // Example condition, refine based on role prop if available
            <div className="card-soft p-6 flex items-center justify-between">
              <div>
                <h3 className="font-bold text-slate-800">Estado Oficial</h3>
                <p className="text-xs text-slate-400">Publicar en App</p>
              </div>
              <button
                onClick={() => toggleActivePlan(selectedPlan.id)}
                className={`relative w-14 h-8 rounded-full transition-colors duration-300 ${selectedPlan.isActive ? 'bg-green-500' : 'bg-slate-200'
                  }`}
              >
                <div className={`absolute top-1 left-1 w-6 h-6 bg-white rounded-full shadow-md transform transition-transform duration-300 ${selectedPlan.isActive ? 'translate-x-6' : 'translate-x-0'
                  }`} />
              </button>
            </div>
          )}

          {/* Team Widget */}
          <div className="bg-white p-6 rounded-[2.5rem] shadow-sm border border-slate-100">
            <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
              <UserCheck className="text-indigo-500" size={20} /> Equipo de Turno
            </h3>
            <div className="space-y-4">
              {ROLES_CONFIG.map(role => {
                // Filter users for this role
                const roleUsers = users.filter(u => u.role === role.role);

                return (
                  <div key={role.key}>
                    <div className="flex items-center gap-2 mb-2">
                      <div className={`p-1.5 rounded-lg ${role.color}`}>
                        <role.icon size={14} />
                      </div>
                      <span className="text-xs font-bold text-slate-600 uppercase">{role.label}</span>
                    </div>
                    <select
                      value={(selectedPlan?.team as any)?.[role.key] || ''}
                      onChange={(e) => handleTeamUpdate(role.key, e.target.value)}
                      className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-indigo-500 text-sm font-medium text-slate-700"
                    >
                      <option value="">Seleccionar...</option>
                      {roleUsers.map(u => (
                        <option key={u.id} value={u.name}>{u.name}</option>
                      ))}
                      {/* Fallback if current assigned user is not in list */}
                      {(selectedPlan?.team as any)?.[role.key] && !roleUsers.find(u => u.name === (selectedPlan?.team as any)?.[role.key]) && (
                        <option value={(selectedPlan?.team as any)?.[role.key]}>{(selectedPlan?.team as any)?.[role.key]}</option>
                      )}
                    </select>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right Col: Timeline */}
        <div className="lg:col-span-2 space-y-4">
          {timelineItems.map((item, index) => (
            <div key={item.id} className="group relative card-soft p-6 hover:shadow-md transition-all">
              <div className="flex items-start gap-4">
                {/* Time */}
                <div className="min-w-[4rem] text-center pt-1">
                  <span className="block text-lg font-bold text-slate-700">{item.calculatedTime}</span>
                  <span className="text-xs text-slate-400">{item.durationMinutes} min</span>
                </div>

                {/* Content */}
                <div className="flex-1 border-l-2 border-slate-100 pl-4">
                  <div className="flex justify-between items-start">
                    <div>
                      <span className={`inline-block px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider mb-1 ${item.type === 'WORSHIP' ? 'bg-pink-50 text-pink-600' :
                        item.type === 'PREACHING' ? 'bg-indigo-50 text-indigo-600' : 'bg-slate-100 text-slate-500'
                        }`}>
                        {item.type}
                      </span>
                      <h4 className="text-lg font-bold text-slate-800">{item.title}</h4>
                    </div>
                    <button
                      onClick={async () => {
                        if (!selectedPlan) return;
                        if (confirm('¿Eliminar este elemento?')) {
                          const updatedItems = selectedPlan.items.filter(i => i.id !== item.id);
                          await savePlan({ ...selectedPlan, items: updatedItems });
                        }
                      }}
                      className="text-slate-300 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>

                  {/* Item Specifics */}
                  {item.type === 'WORSHIP' && (
                    <div className="mt-3 flex flex-col gap-3">
                      <div className="flex gap-3">
                        <div className="px-3 py-1 bg-slate-50 rounded-xl text-xs font-semibold text-slate-600 border border-slate-200">
                          Key: {item.key || 'C'}
                        </div>
                        {item.youtubeLink && (
                          <a href={item.youtubeLink} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs text-red-500 font-medium hover:underline">
                            <PlayCircle size={14} /> Ver Referencia
                          </a>
                        )}
                      </div>

                      {/* Link Input */}
                      {(item.youtubeLinks?.length || 0) < 5 && (
                        <div className="flex gap-2">
                          <input
                            type="text"
                            placeholder="Pegar link de YouTube y presionar Enter..."
                            className="flex-1 px-3 py-2 bg-white border border-slate-200 rounded-lg text-xs outline-none focus:border-indigo-500 transition-all"
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') {
                                const val = e.currentTarget.value;
                                if (val) {
                                  const newLinks = [...(item.youtubeLinks || []), val];
                                  const updatedItems = selectedPlan.items.map(i =>
                                    i.id === item.id ? { ...i, youtubeLinks: newLinks } : i
                                  );
                                  savePlan({ ...selectedPlan, items: updatedItems });
                                  e.currentTarget.value = '';
                                }
                              }
                            }}
                          />
                        </div>
                      )}

                      {/* Links List */}
                      <div className="space-y-2">
                        {item.youtubeLinks?.map((link, linkIdx) => (
                          <div key={linkIdx} className="flex items-center justify-between bg-white px-3 py-2 rounded-lg border border-slate-200 group">
                            <a href={link} target="_blank" rel="noopener noreferrer" className="text-xs text-indigo-600 hover:underline truncate max-w-[200px] flex items-center gap-2">
                              <PlayCircle size={12} /> {link}
                            </a>
                            <button
                              onClick={() => {
                                const newLinks = item.youtubeLinks?.filter((_, i) => i !== linkIdx);
                                const updatedItems = selectedPlan.items.map(i =>
                                  i.id === item.id ? { ...i, youtubeLinks: newLinks } : i
                                );
                                savePlan({ ...selectedPlan, items: updatedItems });
                              }}
                              className="text-slate-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                            >
                              <X size={14} />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {item.type === 'PREACHING' && (
                    <div className="mt-4 bg-indigo-50/50 rounded-2xl p-4 border border-indigo-100">
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-xs font-bold text-indigo-400 uppercase">Notas & Bosquejo</span>
                        {canUseAI ? (
                          <button
                            onClick={() => openAiModal(item.id)}
                            className="flex items-center gap-1 text-xs bg-indigo-600 text-white px-3 py-1.5 rounded-lg shadow-sm shadow-indigo-200 hover:bg-indigo-700 transition-colors"
                          >
                            <Wand2 size={12} /> Generar con IA
                          </button>
                        ) : (
                          <div className="flex items-center gap-1 text-xs text-slate-400 bg-slate-200 px-3 py-1.5 rounded-lg cursor-not-allowed">
                            <Lock size={12} /> Plan Platinum
                          </div>
                        )}
                      </div>
                      <div className="text-sm text-slate-600 whitespace-pre-wrap font-serif">
                        {item.notes || <span className="text-slate-400 italic">No hay notas. {canUseAI ? 'Usa el asistente de IA para comenzar.' : 'Actualiza a Platinum para usar IA.'}</span>}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}

          <button
            onClick={() => setShowAddItemModal(true)}
            className="w-full py-4 border-2 border-dashed border-slate-200 rounded-3xl text-slate-400 font-semibold hover:border-indigo-300 hover:text-indigo-500 transition-colors flex items-center justify-center gap-2"
          >
            <Plus size={20} /> Añadir Ítem
          </button>
        </div>
      </div>

      {/* Add Item Modal */}
      {
        showAddItemModal && (
          <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-[2rem] w-full max-w-2xl p-8 shadow-2xl animate-in fade-in zoom-in duration-200 max-h-[90vh] overflow-y-auto custom-scrollbar">
              <div className="flex justify-between items-center mb-6">
                <div>
                  <h3 className="text-2xl font-bold text-slate-800">Añadir Elemento</h3>
                  <p className="text-slate-500 text-sm">Selecciona una plantilla o crea uno personalizado.</p>
                </div>
                <button onClick={() => setShowAddItemModal(false)} className="p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-400 hover:text-slate-600">
                  <X size={24} />
                </button>
              </div>

              {/* Presets Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3 mb-8">
                {[
                  { label: 'Bienvenida', duration: 5, icon: Hand, type: 'GENERIC', color: 'text-orange-500 bg-orange-50' },
                  { label: 'Alabanza', duration: 20, icon: Music, type: 'WORSHIP', color: 'text-pink-500 bg-pink-50' },
                  { label: 'Oración', duration: 5, icon: UserIcon, type: 'GENERIC', color: 'text-blue-500 bg-blue-50' },
                  { label: 'Lectura', duration: 5, icon: BookOpen, type: 'GENERIC', color: 'text-indigo-500 bg-indigo-50' },
                  { label: 'Predicación', duration: 40, icon: Mic2, type: 'PREACHING', color: 'text-violet-500 bg-violet-50' },
                  { label: 'Ofrenda', duration: 10, icon: DollarSign, type: 'GENERIC', color: 'text-green-500 bg-green-50' },
                  { label: 'Anuncios', duration: 5, icon: Megaphone, type: 'GENERIC', color: 'text-red-500 bg-red-50' },
                  { label: 'Cena Señor', duration: 15, icon: Gift, type: 'GENERIC', color: 'text-amber-500 bg-amber-50' },
                  { label: 'Especial', duration: 5, icon: Star, type: 'GENERIC', color: 'text-yellow-500 bg-yellow-50' },
                  { label: 'Testimonios', duration: 10, icon: MessageCircle, type: 'GENERIC', color: 'text-teal-500 bg-teal-50' },
                  { label: 'Enfermos', duration: 10, icon: Heart, type: 'GENERIC', color: 'text-rose-500 bg-rose-50' },
                  { label: 'Personalizado', duration: 5, icon: PenTool, type: 'GENERIC', color: 'text-slate-500 bg-slate-100', isCustom: true },
                ].map((preset) => (
                  <button
                    key={preset.label}
                    onClick={() => {
                      setNewItem({
                        title: preset.isCustom ? '' : preset.label,
                        durationMinutes: preset.duration,
                        type: preset.type as any,
                        key: ''
                      });
                    }}
                    className="flex flex-col items-center justify-center p-4 rounded-2xl border border-slate-100 hover:border-indigo-300 hover:shadow-md transition-all group bg-white"
                  >
                    <div className={`w-10 h-10 rounded-full flex items-center justify-center mb-2 ${preset.color} group-hover:scale-110 transition-transform`}>
                      <preset.icon size={20} />
                    </div>
                    <span className="text-xs font-bold text-slate-600">{preset.label}</span>
                    <span className="text-[10px] text-slate-400">{preset.duration} min</span>
                  </button>
                ))}
              </div>

              {/* Edit Section */}
              <div className="bg-slate-50 rounded-3xl p-6 border border-slate-100 space-y-4">
                <h4 className="text-sm font-bold text-slate-500 uppercase mb-2">Detalles del Elemento</h4>

                <div>
                  <label className="block text-xs font-bold text-slate-500 mb-1">Título</label>
                  <input
                    type="text"
                    value={newItem.title}
                    onChange={(e) => setNewItem({ ...newItem, title: e.target.value })}
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all font-medium"
                    placeholder="Escribe el nombre del elemento..."
                  />
                </div>

                <div className="flex gap-4">
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-slate-500 mb-1">Duración (minutos)</label>
                    <input
                      type="number"
                      value={newItem.durationMinutes}
                      onChange={(e) => setNewItem({ ...newItem, durationMinutes: parseInt(e.target.value) || 0 })}
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all font-medium"
                    />
                  </div>

                  {newItem.type === 'WORSHIP' && (
                    <div className="flex-1 animate-in slide-in-from-left duration-300">
                      <label className="block text-xs font-bold text-slate-500 mb-1">Tonalidad (Key)</label>
                      <input
                        type="text"
                        value={newItem.key || ''}
                        onChange={(e) => setNewItem({ ...newItem, key: e.target.value })}
                        className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all font-medium"
                        placeholder="Ej. G, Dm, Bb..."
                      />
                    </div>
                  )}
                </div>

                <div className="pt-4">
                  <button
                    onClick={handleAddItem}
                    disabled={!newItem.title}
                    className="w-full py-4 bg-indigo-600 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 hover:scale-[1.01] active:scale-[0.99] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  >
                    <Plus size={20} /> Añadir al Orden
                  </button>
                </div>
              </div>

            </div>
          </div>
        )
      }

      {/* AI Modal */}
      {
        showAiModal && (
          <div className="fixed inset-0 bg-black/30 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-[2rem] w-full max-w-lg p-8 shadow-2xl animate-in fade-in zoom-in duration-200">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center text-indigo-600">
                  <Wand2 size={20} />
                </div>
                <h3 className="text-xl font-bold text-slate-800">Asistente Levita AI</h3>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-600 mb-2">Pasaje Bíblico</label>
                  <input
                    type="text"
                    value={aiParams.passage}
                    onChange={(e) => setAiParams({ ...aiParams, passage: e.target.value })}
                    placeholder="Ej. Salmos 23:1-4"
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-600 mb-2">Tono del Sermón</label>
                  <select
                    value={aiParams.tone}
                    onChange={(e) => setAiParams({ ...aiParams, tone: e.target.value })}
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-indigo-500"
                  >
                    <option>Exhortativo</option>
                    <option>Consolador</option>
                    <option>Evangelístico</option>
                    <option>Doctrinal</option>
                    <option>Narrativo</option>
                  </select>
                </div>
              </div>

              <div className="flex gap-3 mt-8">
                <button
                  onClick={() => setShowAiModal(false)}
                  className="flex-1 py-3 text-slate-500 font-semibold hover:bg-slate-50 rounded-xl transition-colors"
                >
                  Cancelar
                </button>
                <button
                  onClick={handleAiGenerate}
                  disabled={isAiLoading || !aiParams.passage}
                  className="flex-1 py-3 bg-gradient-to-r from-indigo-500 to-purple-500 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 hover:shadow-xl hover:scale-[1.02] transition-all disabled:opacity-50 disabled:scale-100"
                >
                  {isAiLoading ? 'Generando...' : 'Generar Bosquejo'}
                </button>
              </div>
            </div>
          </div>
        )
      }
    </div >
  );
};

export default ServicePlanner;
